### ISSUE TITLE
Resuming from my headset sometimes restarts the episode. 

### ISSUE THREAD

**Issue by Ankhwatcher** [mr3y-the-programmer/Podcaster#31]
🐛 **Describe the bug**
If I pause for an extended period say 5 - 15 minutes and then resume from my headset the episode restarts. 

**App Version**: v1.2.0 - #4 (ab9d94a)

**Comment by mr3y-the-programmer** [comment]
Thanks for reporting the issue! I will investigate it. is this issue reproducible only when you resume from headset not from the UI or the notification drawer?
